### ISSUE TITLE
Readme how to build?

### ISSUE THREAD

**Issue by darkon76** [ringrunnermg/Ringcon-Driver#4]
The readme lacks the steps to build the project, how can it be build?

**Comment by Lonce32** [comment]
Once you've downloaded the project export the files then click Ringcon Driver 19-12-2020 is should say the file type is "File folder" then click Ringcon Driver the file type is "application" then you should be good to go

**Comment by ringrunnermg** [comment]
It is not easy to build, the Joycon driver I based it off had build issues which I did not end up fixing. 

You will likely need to retarget the solution to match the windows sdk you have, then you will need to manually install the project dependencies (hidapi, wxwidgets, vigem, etc). https://vcpkg.io can make getting most of the dependencies easier.

**Comment by ringrunnermg** [comment]
A Korean twitch user https://www.twitch.tv/jungtaejune has written some instructions that are more succinct than I could do.    https://tgd.kr/s/jungtaejune/56363367.

Google translation:

1. First, run Visual Studio Installer and install the English language pack.

2. Install the linked library using vcpkg. (Just run it in cmd window)

Since it is saved directly in the git clone directory, move to the appropriate directory and execute the following command (do not delete the vcpkg folder)

git clone https://github.com/Microsoft/vcpkg.git

cd vcpkg

bootstrap-vcpkg.bat

3. Start -> Search for 'Environment Variables' -> Click 'Edit System Environment Variables' -> Click 'Environment Variables' -> Specify the vcpkg folder in a variable named Path or PATH 

4. Turn off and on the cmd window and enter the following commands sequentially

vcpkg install wxwidgets socket-io-client glm hidapi

git clone https://github.com/ViGEm/ViGEmClient.vcpkg.git C:\ViGEmClient.vcpkg

vcpkg install vigemclient:x86-windows vigemclient:x64-windows --overlay-ports="C:\ViGEmClient.vcpkg"

vcpkg integrate install

5. Open Ringcon Driver with Visual Studio 2019 and build as x86

6. If successful, an executable file is created in the Debug or Release directory in the Ringcon Driver folder.

A config.txt file is required, so remove/copy the config.txt file from the latest release.

If you run it, it will show that there is no DLL file, but if you copy and paste all the dll files in the installed\x86-windows\bin directory in the vcpkg installation folder, it will be executed.

**Comment by darkon76** [comment]
Thanks for the tutorial
